### PR TITLE
Initial structure for monorepo

### PR DESCRIPTION
**Pull request by abhishekgahlot**

### CODE REVIEW

**Comment by rufuspollock** [comment]
@abhishekgahlot is this ready for merging? Tests are failing.

**Comment by anuveyatsu** [comment]
@abhishekgahlot any updates here?

**Comment by rufuspollock** [comment]
@abhishekgahlot update?

**Comment by abhishekgahlot** [comment]
@anuveyatsu @rufuspollock there have been an overflow from Friday deadline. I am opening a new PR now as this one is quite complicated to rebase after the refactoring.

**Pull request closed without merging**
