### PR TITLE
Fix/gqlquery

### LINKED ISSUE #49: Error Loading Dataset resources
An error occurs when trying to view Dataset resources.

error

### PR DESCRIPTION
**Pull request by steveoni**
This Pull request fixes #49 issue. Now possible to load Dataset resources for both the mock dataset and that on ckan.

The error fix by this pull request is due to the grapql query requesting for fields not present in the api

### CODE REVIEW

**Comment by rufuspollock** [comment]
@steveoni great you have a pull request and i'm removing myself as a reviewer as i'm not an expert here 😄

**Comment by steveoni** [comment]
> @steveoni great you have a pull request and i'm removing myself as a reviewer as i'm not an expert here

:smile: ok

**Comment by rufuspollock** [comment]
@steveoni any idea why cypress tests failed?

**Comment by rufuspollock** [comment]
@cotts could you review this?

**Review by cotts — APPROVED** [review]
looks good

**Pull request merged**
