### PR TITLE
Refactor portal.js and merged with portal-experiment

### LINKED ISSUE #59: Move portal-experiment into portal and refactor
Move and refactor [portal-experiment](https://github.com/datopian/portal-experiment) into[ portal.js](https://github.com/datopian/portal.js)

We already have older `packages/portal` which is currently more of an example of a full data catalog site running on nextjs. We want to keep this and move it to `examples/catalog`

Our new `portal` experiment should then become the main `portal` package in `packages/portal` so we can focus on developing there. 

## Acceptance

* [x] `packages/portal` moved to examples/catalog **DONE**
* [x] I have portal-experiment integrated into portal.js repo **DONE. located at `packages/portal`. Have also integrated the CLI into that package.**
* [x] updated main README to reflect this **DONE. Main README is stubbed atm**

## Task

* [x]  Agree on repo we are using **DONE.** We agreed to move [portal-experiment](https://github.com/datopian/portal-experiment) into[ portal.js](https://github.com/datopian/portal.js)
* [x]  Clean up the portal repo
  * [x]  Move packages/portal to examples/catalog
  * [x]  Refactor README to explain this is an example
  * [x]  Reboot portal sub package with README

### PR DESCRIPTION
**Pull request by risenW**
This pull fixes #59

### CODE REVIEW

**Comment by rufuspollock** [comment]
@risenW I think there is a bit of confusion here as to what was expected ...

* No need for oldPortal
* create-portal-app should remain (no need to move that)

In summary:

```
# current portal package moves to examples
# then fix its README a bit
packages/portal => examples/catalog

# portal-experiment moves in (if you can merge commit history that's a bonus - if not don't worry)
portal-experiment repo contents => packages/portal
```

Does that make sense?

**Comment by rufuspollock** [comment]
PS: rather than do more in this PR i would recommend starting again so you get clean changes.

(And sorry for not being clearer in my notes on this)

**Comment by risenW** [comment]
> @risenW I think there is a bit of confusion here as to what was expected ...
> 
> * No need for oldPortal
> * create-portal-app should remain (no need to move that)
> 
> In summary:
> 
> ```
> # current portal package moves to examples
> # then fix its README a bit
> packages/portal => examples/catalog
> 
> # portal-experiment moves in (if you can merge commit history that's a bonus - if not don't worry)
> portal-experiment repo contents => packages/portal
> ```
> 
> Does that make sense?

Okay, yes it does make sense now.

**Comment by risenW** [comment]
@rufuspollock create-portal-app is basically doing what [portal-cli-app](https://github.com/datopian/portal-cli-app) will be doing. Do we still need it here?

**Comment by risenW** [comment]
> @rufuspollock create-portal-app is basically doing what [portal-cli-app](https://github.com/datopian/portal-cli-app) will be doing. Do we still need it here?

@anuveyatsu Has answered this. His answer was that we leave the create-portal-app as it is different from portal-cli-app.

**Comment by risenW** [comment]
WONTMERGE: Refactoring is now happening in this pull #62 and this is obsolete

**Comment by rufuspollock** [comment]
@risenW clear now and if we are going the monorepo approach i would suggest that https://github.com/datopian/portal-cli-app be part of this repo in packages (unless good reason to be separate?)

**Comment by risenW** [comment]
> @risenW clear now and if we are going the monorepo approach i would suggest that https://github.com/datopian/portal-cli-app be part of this repo in packages (unless good reason to be separate?)

The main reason I separated it was size. Since when we run portal show, we clone the portal.js repo first, having extra files  and folder just repo to the size.

**Pull request closed without merging**
